# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KIadroviiInfrastruktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Broj_zaposlenih', models.IntegerField(help_text='Унети приближан број запослених', verbose_name='Наведите број запослених који раде на прикупљању, обради или коришћењу просторних података.')),
                ('Navesti_organizacionu_jedinicu', models.CharField(help_text='нпр.Одељење за ГИС', max_length=100, verbose_name='Навести организациону јединицу у чијој су надлежности послови у вези са просторним подацима уколико постоји')),
                ('Procenite_znacaj_upotrebe_geoinformacija', models.CharField(choices=[('Суштински', 'Суштински'), ('Веома Користан', 'Веома Користан'), ('Користан', 'Користан'), ('Користан у мањој мери', 'Користан у мањој мери')], max_length=100, verbose_name='Процените значај геоинформација за пословање ваше организације')),
                ('Glavne_prepreke_za_koriscenje_geoinformacija', models.CharField(choices=[('Недостатак квалификованог особља', 'Недостатак квалификованог особља'), ('Недостатак ИТ капацитета', 'Недостатак ИТ капацитета(софтвер, опрема)'), ('Недостатак података', 'Недостатак података(недоступни подаци, скушпо финансирање)'), ('Остало', 'Остало')], max_length=100)),
                ('Serveri_za_prostorne_podatke', models.CharField(choices=[('ArcGIS Server (ESRI)', 'ArcGIS Server (ESRI)'), ('Autodesk Infrastructure Map Server', 'Autodesk Infrastructure Map Server'), ('GeoServer', 'GeoServer'), ('MapServer', 'MapServer'), ('ERDAS APOLLO', 'ERDAS APOLLO'), ('Остало', 'Остало')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pitanje2_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(choices=[('ArcGIS Desktop (ESRI)', 'ArcGIS Desktop (ESRI)'), ('Q GIS', 'Q GIS'), ('MapInfo', 'ArcGIS Desktop (ESRI)'), ('GeoMedia', 'GeoMedia'), ('MapSoft', 'MapSoft'), ('AutoCAD', 'AutoCAD'), ('Bently MicroStation', 'Bently MicroStation'), ('ERDAS IMAGINE', 'ERDAS IMAGINE'), ('Leica Photogrametry Suite', 'Leica Photogrametry Suite'), ('eCognition Trimble', 'eCognition Trimble'), ('Интерно креиране апликације', 'Интерно креиране апликације'), ('Остало', 'Остало')], max_length=100)),
                ('Namena', models.CharField(choices=[('Израда планова и карата', 'Израда планова и карата'), ('Пројектовање', 'Пројектовање'), ('Извештавање', 'Извештавање'), ('Управљање и планирање коришћења земљишта', 'Управљање и планирање коришћења земљишта'), ('Урбанизам и грађевински послови', 'Урбанизам и грађевински послови'), ('Праћење промена и просторне анализе', 'Праћење промена и просторне анализе'), ('Креирање и анализа ДМТ', 'Креирање и анализа ДМТ'), ('Геореференцирање и обрада растерских података', 'Геореференцирање и обрада растерских података'), ('Даљинска детекција', 'Даљинска детекција'), ('Обрада података добијених ласерским скенирањем', 'Обрада података добијених ласерским скенирањем'), ('Остало', 'Остало')], max_length=100)),
                ('Ucestalost_Koriscenja', models.CharField(choices=[('Свакодневно', 'Свакодневно'), ('Често за обимније анализе', 'Често за обимније анализе'), ('Понекад за посебне анализе и извештаје', 'Понекад за посебне анализе и извештаје')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pitanje2_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(choices=[('MS Access', 'MS Access'), ('Oracle ', 'Oracle '), ('PostgreSQL', 'PostgreSQL'), ('MicrosoftSQL', 'MicrosoftSQL'), ('Остало', 'Остало')], max_length=100)),
                ('Namena', models.CharField(choices=[('Складиштење просторних података', 'Складиштење просторних података'), ('Складиштење алфанумеричких података', 'Складиштење алфанумеричких података'), ('Остало', 'Остало')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pitanje2_8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(choices=[('ArcPAD', 'ArcPAD'), ('Leica Zeno', 'Leica Zeno'), ('Интерно креиране апликације', 'Интерно креиране апликације'), ('Остало', 'Остало')], max_length=100)),
                ('Namena', models.CharField(choices=[('Прикупљање података са терена', 'Прикупљање података са терена'), ('Праћење возила', 'Праћење возила'), ('Остало', 'Остало')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='kiadroviiinfrastruktura',
            name='Koje_aplikacije_su_u_upotrebi_za_obradu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje2_5'),
        ),
        migrations.AddField(
            model_name='kiadroviiinfrastruktura',
            name='Koji_sistemi_za_upravljanje_bazama_imate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje2_6'),
        ),
        migrations.AddField(
            model_name='kiadroviiinfrastruktura',
            name='Mobilne_gis_aplikacije',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje2_8'),
        ),
    ]
