# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0006_pitanje4_7_saradnjaizmedjusubjekata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitanje5_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inspire', models.CharField(choices=[('Користи се', 'Користи се'), ('Делимично', 'Делимично'), ('Потребно', 'Потребно'), ('Не користи се', 'Не користи се'), ('Нисмо упознати са стандардом', 'Нисмо упознати са стандардом')], max_length=100)),
                ('Iso_i_Cen', models.CharField(choices=[('Користи се', 'Користи се'), ('Делимично', 'Делимично'), ('Потребно', 'Потребно'), ('Не користи се', 'Не користи се'), ('Нисмо упознати са стандардом', 'Нисмо упознати са стандардом')], max_length=100)),
                ('OGC', models.CharField(choices=[('Користи се', 'Користи се'), ('Делимично', 'Делимично'), ('Потребно', 'Потребно'), ('Не користи се', 'Не користи се'), ('Нисмо упознати са стандардом', 'Нисмо упознати са стандардом')], max_length=100)),
                ('W3C', models.CharField(choices=[('Користи се', 'Користи се'), ('Делимично', 'Делимично'), ('Потребно', 'Потребно'), ('Не користи се', 'Не користи се'), ('Нисмо упознати са стандардом', 'Нисмо упознати са стандардом')], max_length=100)),
                ('Standardi_proizvodjaca_gis_softvera', models.CharField(choices=[('Користи се', 'Користи се'), ('Делимично', 'Делимично'), ('Потребно', 'Потребно'), ('Не користи се', 'Не користи се'), ('Нисмо упознати са стандардом', 'Нисмо упознати са стандардом')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pitanje5_12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prepreka1', models.TextField()),
                ('Prepreka2', models.TextField()),
                ('Prepreka3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitanje5_13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prepreka1', models.CharField(choices=[('Није од значаја', 'Није од значаја'), ('Делимично значајно', 'Делимично значајно'), ('Значајно', 'Значајно'), ('Од великог значаја', 'Од великог значаја'), ('Изузетно значајно', 'Изузетно значајно')], max_length=100)),
                ('Prepreka2', models.CharField(choices=[('Није од значаја', 'Није од значаја'), ('Делимично значајно', 'Делимично значајно'), ('Значајно', 'Значајно'), ('Од великог значаја', 'Од великог значаја'), ('Изузетно значајно', 'Изузетно значајно')], max_length=100)),
                ('Prepreka3', models.CharField(choices=[('Није од значаја', 'Није од значаја'), ('Делимично значајно', 'Делимично значајно'), ('Значајно', 'Значајно'), ('Од великог значаја', 'Од великог значаја'), ('Изузетно значајно', 'Изузетно значајно')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pitanje5_14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Otvoreni_podaci_ce_dobrineti_razvoju_lokalnih_samouprave', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Otvoreni_podaci_ce_omoguciti_efikasniju_drzavnu_administraciju', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Otvoreni_podaci_ce_dobrineti_razvoju_koriscenja_podataka', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Otvoreni_podaci_ce_dobrineti_boljem_razumevanju_drzavne_uprave', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Otvoreni_podaci_mogu_da_se_koriste_u_druge_svrhe', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Korisnici_koji_nisu_u_boljem_razumevanju_drzavne_uprave', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Svi_podaci_u_konceptu_open_data', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Postoji_puno_razloga_da_podaci_ne_budu_opendata', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Efikiasnija_i_brza_razmena_podataka', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Efikasnija_i_povoljinja_administracija', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Kvalitetnije_izvestavanje_ka_evropskim_institucijama', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Koristan_za_celokupnu_zajednicu', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Manja_redudantnost_podataka', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Dostupni_u_pogodnom_obliku', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Koriscenje_izvan_podrucja_namene', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
                ('Kreirati_servis_za_pronalazenje_podataka', models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pitanje5_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Standard', models.CharField(max_length=100)),
                ('Upotreba', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitanje5_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Da_ne', models.NullBooleanField()),
                ('Naziv_akta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StandardizacijaOtvorenihPodataka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metode_koriscenja_i_zastite', models.CharField(choices=[('copyright', 'copyright'), ('ауторизација приступа', 'ауторизација приступа'), ('бекап', 'бекап'), ('ограничена права приступа ', 'ограничена права приступа '), ('GеоDRM', 'GеоDRM – Digital Right Management'), ('Друго', 'Друго')], max_length=100)),
                ('Da_li_podrzavate_prikupljanje_geopodataka_prema_konceptu_otvorenih_podataka', models.CharField(choices=[('Да ', 'Да '), ('Не', 'Не'), ('Друго', 'Друго')], max_length=100)),
                ('Da_li_ste_upoznati_sa_nekim_od_postojecih_portala', models.CharField(choices=[('data.gov.rs', 'Национални OpenData портал (data.gov.rs) '), ('data.poverenik.rs', 'Портал отворених података Повереника за информације од јавног значаја и заштиту података о личности (data.poverenik.rs)'), ('SHARE', 'Платформа SHARE фондације'), ('Друго', 'Друго')], max_length=100)),
                ('Da_li_ste_koristili_besplatne_setove_podataka', models.CharField(choices=[('OpenData ', 'Користили смо, преузимањем са националног OpenData портала '), ('Преуѕимање са других портала', 'Користили смо, преузимањем са других постојећих портала'), ('Стандардни начин', 'Користили смо, преузимањем на стандардан начин (дигитални медиј, папир, поштом, преко имејла, и сл.)'), ('Нисмо користили', 'Нисмо користили, планирамо интензивније коришћење отворених података у будућности'), ('Друго', 'Друго')], max_length=100)),
                ('Za_koje_poslove_ste_koristili_podatke', models.CharField(choices=[('Креирање web сајта или мобилне апликације ', 'Креирање web сајта или мобилне апликације '), ('Креирање web сервиса', 'Креирање web сервиса'), ('Извештаји, радови или презентације', 'Извештаји, радови или презентације'), ('Интеграција са већ постојећим web сајтовима или мобилним апликацијама', 'Интеграција са већ постојећим web сајтовима или мобилним апликацијама'), ('Креирање тематских карата или сличних визуелизација отворених података', 'Креирање тематских карата или сличних визуелизација отворених података'), ('Статистичке анализе', 'Статистичке анализе'), ('Друго', 'Друго')], max_length=100)),
                ('Format_podataka', models.CharField(choices=[('CSV', 'Comma Separated Values file format (*.csv) '), ('XLS', 'Microsoft Excel file format (*.xls)'), ('PDF', 'Adobe PDF (*.pdf)'), ('TIFF', 'Tagged Image File Format (*.tif)'), ('CDR', 'CorelDraw file format (*.cdr)'), ('SHP', 'ESRI shapefile (*.shp)'), ('XML', 'Extensible Markup Language (*.xml)'), ('KML', 'Keyhole Markup Language (*.kml, *.kmz)'), ('DXF', 'AutoCAD file format (*.dxf)'), ('JSON', 'JavaScript Object Notation (*.json)'), ('Друго', 'Друго')], max_length=100)),
                ('Koju_vrstu_podataka_ste_koristili', models.CharField(choices=[('Геоподаци ', 'Геоподаци '), ('Финансијски подаци', 'Финансијски подаци'), ('Статистички подаци', 'Статистички подаци'), ('Научни подаци', 'Научни подаци'), ('Подаци о времену', 'Подаци о времену'), ('Подаци о култури', 'Подаци о култури'), ('Подаци о животној средини', 'Подаци о животној средини'), ('Подаци јавног сектора', 'Подаци јавног сектора'), ('Друго', 'Друго')], max_length=100)),
                ('Opis_projekta_sa_prostornim_podacima', models.TextField()),
                ('Sufinansiranje_podataka', models.CharField(choices=[('Да', 'Да, заинтересовани смо да учествујемо у суфинансирању'), ('Не', 'Не, нисмо заинтересовани да учествујемо у суфинансирању'), ('Друго', 'Друго')], max_length=100)),
                ('Koliko_se_slazete_sa_tvrdnjama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_14')),
                ('Prepreke_za_uspostavljanje_koncepta_gopodataka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_12')),
                ('Propis_prava_koriscenja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_4')),
                ('Standardi_iz_oblasti_geoinformacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_2')),
                ('Status_standarda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_1')),
                ('Vaznost_Prepreka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_13')),
            ],
        ),
    ]
