# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0010_auto_20170720_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitanje3_1',
            name='NN',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
    ]
