# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0011_pitanje3_1_nn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitanje3_1',
            name='NN',
        ),
        migrations.AlterField(
            model_name='prostornipodaci',
            name='Za_koje_od_navedenih_INSPIRE_tema_proizvodite_podatke',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje3_1'),
        ),
    ]
