# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0018_auto_20170728_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pitanja.FamilyMember'),
        ),
    ]
