# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0020_auto_20170801_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sveobuhvatnimodel',
            name='Cetvrta_sekcija',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='pitanja.SaradnjaIzmedjuSubjekata'),
        ),
        migrations.AlterField(
            model_name='sveobuhvatnimodel',
            name='Druga_sekcija',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='pitanja.KadroviInfrastruktura'),
        ),
        migrations.AlterField(
            model_name='sveobuhvatnimodel',
            name='Peta_sekcija',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='pitanja.StandardizacijaOtvorenihPodataka'),
        ),
        migrations.AlterField(
            model_name='sveobuhvatnimodel',
            name='Prva_sekcija',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='pitanja.OrganizacijaOsnovniPodaci'),
        ),
        migrations.AlterField(
            model_name='sveobuhvatnimodel',
            name='Treca_sekcija',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='pitanja.ProstorniPodaci'),
        ),
    ]
