# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0021_auto_20170804_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sveobuhvatnimodel',
            name='Cetvrta_sekcija',
        ),
    ]
