# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0022_remove_sveobuhvatnimodel_cetvrta_sekcija'),
    ]

    operations = [
        migrations.AddField(
            model_name='sveobuhvatnimodel',
            name='Cetvrta_sekcija',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='pitanja.SaradnjaIzmedjuSubjekata'),
        ),
    ]
