# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0024_auto_20170807_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Dostupni_u_pogodnom_obliku',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Подаци морају бити доступни у погодном облику који је могуће мењати'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Efikasnija_i_povoljinja_administracija',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Отворени подаци ће допринети ефикаснијој и повољнијој администрацији у оквиру државне управе'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Efikiasnija_i_brza_razmena_podataka',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Отворени подаци ће допринети ефикаснијој и бржој размени података'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Koriscenje_izvan_podrucja_namene',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Подаци морају имати дозволу за коришћење изван изворног подручја намене и редистрибуцију укључујући укрштање с другим скуповима података'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Korisnici_koji_nisu_u_boljem_razumevanju_drzavne_uprave',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Корисници који нису у систему државне управе могу боље да искористе податке него органи државне управе'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Koristan_za_celokupnu_zajednicu',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Концепт отворених података је вишеструко користан за целокупну друштвену заједницу'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Kreirati_servis_za_pronalazenje_podataka',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Потребно је креирати сервис за проналажење доступних података који би омогућио боље коришћење отворених података'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Kvalitetnije_izvestavanje_ka_evropskim_institucijama',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Отворени подаци ће допринети квалитетнијим извештавањем према државним и Европским институцијама'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Manja_redudantnost_podataka',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Концепт отворених података би допринео мањој редудантности података у државном сектору'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Otvoreni_podaci_ce_dobrineti_boljem_razumevanju_drzavne_uprave',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Отворени подаци ће допринети бољем разумевању државне управе'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Otvoreni_podaci_ce_dobrineti_razvoju_koriscenja_podataka',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Отворени подаци ће допринети развоју коришћења просторних и других података'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Otvoreni_podaci_ce_dobrineti_razvoju_lokalnih_samouprave',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Отворени подаци ће допринети развоју локалних самоуправа'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Otvoreni_podaci_ce_omoguciti_efikasniju_drzavnu_administraciju',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Отворени подаци ће омогућити ефикаснију државну админстрацију'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Otvoreni_podaci_mogu_da_se_koriste_u_druge_svrhe',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Отворени подаци могу да се користе у комерцијалне сврхе'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Postoji_puno_razloga_da_podaci_ne_budu_opendata',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Постоји пуно разлога због чега не треба сви просторни подаци да буду у концепту опен дата'),
        ),
        migrations.AlterField(
            model_name='pitanje5_14',
            name='Svi_podaci_u_konceptu_open_data',
            field=models.CharField(choices=[('Уопште се не слажем', 'Уопште се не слажем'), ('Не слажем се', 'Не слажем се'), ('Неодлучан', 'Неодлучан'), ('Слажем се', 'Слажем се'), ('Потпуно се слажем', 'Потпуно се слажем')], max_length=100, verbose_name='Сви просторни подаци које производе органи државне управе треба да буду у концепту опен дата'),
        ),
    ]
