# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0025_auto_20170816_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadroviinfrastruktura',
            name='Procenite_znacaj_upotrebe_geoinformacija',
            field=models.CharField(choices=[('Суштински', 'Суштински'), ('Веома Користан', 'Веома Користан'), ('Користан', 'Користан'), ('Користан у мањој мери', 'Користан у мањој мери')], max_length=100, verbose_name='Процените значај геоинформација за пословање ваше организације?'),
        ),
        migrations.AlterField(
            model_name='pitanje2_5',
            name='Namena',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Израда планова и карата', 'Израда планова и карата'), ('Пројектовање', 'Пројектовање'), ('Извештавање', 'Извештавање'), ('Управљање и планирање коришћења земљишта', 'Управљање и планирање коришћења земљишта'), ('Урбанизам и грађевински послови', 'Урбанизам и грађевински послови'), ('Праћење промена и просторне анализе', 'Праћење промена и просторне анализе'), ('Креирање и анализа ДМТ', 'Креирање и анализа ДМТ'), ('Геореференцирање и обрада растерских података', 'Геореференцирање и обрада растерских података'), ('Даљинска детекција', 'Даљинска детекција'), ('Обрада података добијених ласерским скенирањем', 'Обрада података добијених ласерским скенирањем'), ('Остало', 'Остало')], max_length=299),
        ),
    ]
