# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0028_auto_20170817_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sekcija2_5_Namena_ChoicesClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namena_choices', models.CharField(choices=[('Израда планова и карата', 'Израда планова и карата'), ('Пројектовање', 'Пројектовање'), ('Извештавање', 'Извештавање'), ('Управљање и планирање коришћења земљишта', 'Управљање и планирање коришћења земљишта'), ('Урбанизам и грађевински послови', 'Урбанизам и грађевински послови'), ('Праћење промена и просторне анализе', 'Праћење промена и просторне анализе'), ('Креирање и анализа ДМТ', 'Креирање и анализа ДМТ'), ('Геореференцирање и обрада растерских података', 'Геореференцирање и обрада растерских података'), ('Даљинска детекција', 'Даљинска детекција'), ('Обрада података добијених ласерским скенирањем', 'Обрада података добијених ласерским скенирањем'), ('Остало', 'Остало')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pitanje2_5',
            name='Namena',
        ),
        migrations.AddField(
            model_name='pitanje2_5',
            name='Namena',
            field=models.ManyToManyField(to='pitanja.Sekcija2_5_Namena_ChoicesClass'),
        ),
    ]
