# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0032_auto_20170817_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitanje2_5',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pitanje2_5',
            name='Namena',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Израда планова и карата', 'Израда планова и карата'), ('Пројектовање', 'Пројектовање'), ('Извештавање', 'Извештавање'), ('Управљање и планирање коришћења земљишта', 'Управљање и планирање коришћења земљишта'), ('Урбанизам и грађевински послови', 'Урбанизам и грађевински послови'), ('Праћење промена и просторне анализе', 'Праћење промена и просторне анализе'), ('Креирање и анализа ДМТ', 'Креирање и анализа ДМТ'), ('Геореференцирање и обрада растерских података', 'Геореференцирање и обрада растерских података'), ('Даљинска детекција', 'Даљинска детекција'), ('Обрада података добијених ласерским скенирањем', 'Обрада података добијених ласерским скенирањем'), ('Остало', 'Остало')], max_length=299, null=True),
        ),
        migrations.AlterField(
            model_name='pitanje2_6',
            name='Namena',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Складиштење просторних података', 'Складиштење просторних података'), ('Складиштење алфанумеричких података', 'Складиштење алфанумеричких података'), ('Остало', 'Остало')], max_length=74, null=True),
        ),
        migrations.AlterField(
            model_name='pitanje2_8',
            name='Namena',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Прикупљање података са терена', 'Прикупљање података са терена'), ('Праћење возила', 'Праћење возила'), ('Остало', 'Остало')], max_length=51, null=True),
        ),
    ]
