# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0033_auto_20170818_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitanje2_5',
            name='Jedinstveni',
        ),
    ]
