# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0036_auto_20170821_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadroviinfrastruktura',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje3_1',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje3_2',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje3_3',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje3_4',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje3_5',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje4_7',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje5_1',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje5_12',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje5_13',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje5_14',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje5_2',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitanje5_4',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prostornipodaci',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saradnjaizmedjusubjekata',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standardizacijaotvorenihpodataka',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
