# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0039_auto_20170821_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitanje3_4',
            name='Jedinstveni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
