# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 13:05
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0044_auto_20170825_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadroviinfrastruktura',
            name='Glavne_prepreke_za_koriscenje_geoinformacija',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Недостатак квалификованог особља', 'Недостатак квалификованог особља'), ('Недостатак ИТ капацитета', 'Недостатак ИТ капацитета(софтвер, опрема)'), ('Недостатак података', 'Недостатак података(недоступни подаци, скушпо финансирање)'), ('Остало', 'Остало')], max_length=84),
        ),
        migrations.AlterField(
            model_name='kadroviinfrastruktura',
            name='Serveri_za_prostorne_podatke',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ArcGIS Server (ESRI)', 'ArcGIS Server (ESRI)'), ('Autodesk Infrastructure Map Server', 'Autodesk Infrastructure Map Server'), ('GeoServer', 'GeoServer'), ('MapServer', 'MapServer'), ('ERDAS APOLLO', 'ERDAS APOLLO'), ('Ostalo', 'Ostalo')], max_length=95),
        ),
        migrations.AlterField(
            model_name='pitanje2_8',
            name='Namena',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Прикупљање података са терена', 'Прикупљање података са терена'), ('Праћење возила', 'Праћење возила'), ('Остало', 'Остало')], max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Dostupnost',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('интерно', 'интерно'), ('доступно свима', 'доступно свима')], max_length=22),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Format_Distribucije',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adobe PDF', 'Adobe PDF (*.pdf)'), ('ASCII gridded', 'ASCII gridded data format (*.xyz)'), ('GeoTIFF', 'GeoTIFF (*.tif)'), ('TIFF', 'TIFF (*.tif)'), ('CorelDraw', 'CorelDraw file format (*.cdr)'), ('TIFF', 'TIFF (*.tif), TFW (*.tfw)'), ('ECW', 'ECW Image file format (*.ecw)'), ('MrSID', 'MrSID file format (*.sid)'), ('ESRI', 'ESRI shapefile (*.shp)'), ('MapInfo ', 'MapInfo TAB format (*.tab)'), ('KML', 'KML file format (*.kml, *.kmz)'), ('IMG ', 'IMG file format (*.img)'), ('NTF', 'NTF Image file format (*.ntf)'), ('AutoCAD DXF', 'AutoCAD DXF (*.dxf)'), ('ESRI file', 'ESRI file geodatabase (*.gdb)'), ('ESRI personal', 'ESRI personal geodatabase (*.mdb)'), ('JPG', 'JPG file format (*.jpg)'), ('Microsoft Excel', 'Microsoft Excel file format (*.xls)'), ('Остало', 'Остало')], max_length=151),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Koordinatni_Sistem',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Гаус-Кригер', 'Гаус-Кригер'), ('ETRS89/UTM', 'ETRS89/UTM'), ('Географски координатни систем', 'Географски координатни систем'), ('Подаци нису просторно одређени', 'Подаци нису просторно одређени - геореференцирани'), ('Ostalo', 'Ostalo')], max_length=90),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Nacin_Distribucije',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Поштом', 'Поштом'), ('Преко имејла', 'Преко имејла'), ('Директно преузимање ', 'Директно преузимање (дигитални медиј, папир)'), ('Преузимање преко интернета', 'Преузимање преко интернета (download: HTTP и FTP )'), ('Web сервиси', 'Web сервиси'), ('Ostalo', 'Ostalo')], max_length=86),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Nacin_skladistenja',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('gdb', 'ESRI file geodatabase (*.gdb)'), ('mdb', 'ESRI personal geodatabase (*.mdb)'), ('MS Access', 'MS Access'), ('Oracle ', 'Oracle '), ('PostgreSQL', 'PostgreSQL'), ('MicrosoftSQL', 'MicrosoftSQL'), ('Фолдерска структура на серверима', 'Фолдерска структура на серверима'), ('Остало', 'Остало')], max_length=89),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Prava_Pristupa',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('интерно', 'интерно'), ('доступно свима', 'доступно свима')], max_length=22),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Web_Servis',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('интерно', 'интерно'), ('доступно свима', 'доступно свима')], max_length=22),
        ),
        migrations.AlterField(
            model_name='saradnjaizmedjusubjekata',
            name='Ko_su_korisnici_vasih_proizvoda',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Сопствене потребе', 'Сопствене потребе'), ('Органи државне управе', 'Органи државне управе'), ('Органи територијалне аутономије', 'Органи територијалне аутономије'), ('Органи локалне самоуправе', 'Органи локалне самоуправе'), ('Јавне агенције', 'Јавне агенције'), ('Јавна предузећа', 'Јавна предузећа'), ('Научно-образовне установе', 'Научно-образовне установе'), ('Пројектантскo-урбанистичке организације', 'Пројектантскo-урбанистичке организације'), ('Приватне организације', 'Приватне организације'), ('Европске и друге међународне институције', 'Европске и друге међународне институције'), ('Грађани', 'Грађани'), ('Друго', 'Друго')], max_length=271),
        ),
        migrations.AlterField(
            model_name='saradnjaizmedjusubjekata',
            name='Koja_je_cenovna_politika_za_geopodatke',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Цена се одређује подзаконским актима или сопственим одлукама', 'Цена се одређује подзаконским актима или сопственим одлукама'), ('Подаци/услуге су бесплатни ', 'Подаци/услуге су бесплатни '), ('Комбиновани модел ', 'Комбиновани модел ')], max_length=107),
        ),
        migrations.AlterField(
            model_name='saradnjaizmedjusubjekata',
            name='Kojem_modelu_finansiranja_NGIPA_treba_teziti',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Покривање трошкова производње из буџета', 'Покривање трошкова производње из буџета за кључне геоподатке, уз размену без накнаде између субјеката НИГП-а'), ('Накнада за коришћење геоподатака према договореним условима', 'Накнада за коришћење геоподатака према договореним условима'), ('Тржишни услови', 'Тржишни услови'), ('Друго', 'Друго')], max_length=120),
        ),
        migrations.AlterField(
            model_name='saradnjaizmedjusubjekata',
            name='Model_odredjivanja_cene',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Покривање трошкова производње', 'Покривање трошкова производње'), ('Тржишна цена', 'Тржишна цена'), ('Друго', 'Друго')], max_length=48),
        ),
        migrations.AlterField(
            model_name='saradnjaizmedjusubjekata',
            name='Na_koji_nacin_obezbedjujete_podatke_za_svoje_potrebe',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Сопствена производња података', 'Сопствена производња података'), ('Набавка кроз пројекте', 'Набавка кроз пројекте'), ('Преузимањем од других државних органа без накнаде', 'Преузимањем од других државних органа без накнаде'), ('Куповина', 'Куповина'), ('Друго', 'Друго')], max_length=116),
        ),
        migrations.AlterField(
            model_name='saradnjaizmedjusubjekata',
            name='Na_koji_nacin_saradjujete_sa_drugim_organizacijama_pri_razmeni',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('По захтеву', 'По захтеву'), ('На основу уговора/споразума', 'На основу уговора/споразума'), ('На основу закона', 'На основу закона'), ('Друго', 'Друго')], max_length=61),
        ),
        migrations.AlterField(
            model_name='saradnjaizmedjusubjekata',
            name='Problemi_prilikom_nabavke_geopodataka',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Непостојање геоподатака у дигиталној форми ', 'Непостојање геоподатака у дигиталној форми '), ('Слабо доступне информације о надлежној организацији за одређене геоподатке', 'Слабо доступне информације о надлежној организацији за одређене геоподатке'), ('Стари/неажурни подаци', 'Стари/неажурни подаци'), ('Некомплетни подаци', 'Некомплетни подаци (просторни обухват и атрибути)'), ('Неодговарајући квалитет података', 'Неодговарајући квалитет података'), ('Високе цене', 'Високе цене'), ('Некомпатибилни формати података', 'Некомпатибилни формати података'), ('Сложене и нејасне процедуре', 'Сложене и нејасне процедуре'), ('Кашњење у испоруци', 'Кашњење у испоруци'), ('Неодговарајућа корисничка подршка', 'Неодговарајућа корисничка подршка'), ('Ограничена права приступа ', 'Ограничена права приступа '), ('Друго', 'Друго')], max_length=350),
        ),
        migrations.AlterField(
            model_name='standardizacijaotvorenihpodataka',
            name='Da_li_ste_koristili_besplatne_setove_podataka',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('OpenData ', 'Користили смо, преузимањем са националног OpenData портала '), ('Преуѕимање са других портала', 'Користили смо, преузимањем са других постојећих портала'), ('Стандардни начин', 'Користили смо, преузимањем на стандардан начин (дигитални медиј, папир, поштом, преко имејла, и сл.)'), ('Нисмо користили', 'Нисмо користили, планирамо интензивније коришћење отворених података у будућности'), ('Друго', 'Друго')], max_length=77),
        ),
        migrations.AlterField(
            model_name='standardizacijaotvorenihpodataka',
            name='Da_li_ste_upoznati_sa_nekim_od_postojecih_portala',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('data.gov.rs', 'Национални OpenData портал (data.gov.rs) '), ('data.poverenik.rs', 'Портал отворених података Повереника за информације од јавног значаја и заштиту података о личности (data.poverenik.rs)'), ('SHARE', 'Платформа SHARE фондације'), ('Друго', 'Друго')], max_length=41),
        ),
        migrations.AlterField(
            model_name='standardizacijaotvorenihpodataka',
            name='Koju_vrstu_podataka_ste_koristili',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Геоподаци ', 'Геоподаци '), ('Финансијски подаци', 'Финансијски подаци'), ('Статистички подаци', 'Статистички подаци'), ('Научни подаци', 'Научни подаци'), ('Подаци о времену', 'Подаци о времену'), ('Подаци о култури', 'Подаци о култури'), ('Подаци о животној средини', 'Подаци о животној средини'), ('Подаци јавног сектора', 'Подаци јавног сектора'), ('Друго', 'Друго')], max_length=150),
        ),
        migrations.AlterField(
            model_name='standardizacijaotvorenihpodataka',
            name='Za_koje_poslove_ste_koristili_podatke',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Креирање web сајта или мобилне апликације ', 'Креирање web сајта или мобилне апликације '), ('Креирање web сервиса', 'Креирање web сервиса'), ('Извештаји, радови или презентације', 'Извештаји, радови или презентације'), ('Интеграција са већ постојећим web сајтовима или мобилним апликацијама', 'Интеграција са већ постојећим web сајтовима или мобилним апликацијама'), ('Креирање тематских карата или сличних визуелизација отворених података', 'Креирање тематских карата или сличних визуелизација отворених података'), ('Статистичке анализе', 'Статистичке анализе'), ('Друго', 'Друго')], max_length=265),
        ),
    ]
