# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0047_auto_20170828_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacijaosnovnipodaci',
            name='Vrsta_organizacije_drugo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Врста организације друго'),
        ),
        migrations.AlterField(
            model_name='saradnjaizmedjusubjekata',
            name='Da_li_Podrzavate_razmenu_podataka_preko_portala_e_placanje',
            field=models.CharField(blank=True, choices=[('Da', 'Да, подржавамо'), ('Ne', 'Не, не подржавамо')], max_length=100, null=True),
        ),
    ]
