# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0048_auto_20170829_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacijaosnovnipodaci',
            name='Glavna_strucna_oblast_vase_organizacije_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Главна стручна област ваше организације друго'),
        ),
        migrations.AddField(
            model_name='organizacijaosnovnipodaci',
            name='Kako_se_vasa_organizacija_finansira_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Како се ваша организација финансира остало'),
        ),
    ]
