# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0049_auto_20170829_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadroviinfrastruktura',
            name='Glavne_prepreke_za_koriscenje_geoinformacija_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Главне препреке за коришћенје геоинформација остало'),
        ),
    ]
