# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0050_kadroviinfrastruktura_glavne_prepreke_za_koriscenje_geoinformacija_ostalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadroviinfrastruktura',
            name='Serveri_za_prostorne_podatke_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сервери за просторне податке остало'),
        ),
        migrations.AddField(
            model_name='prostornipodaci',
            name='Dodatno_obrazovanje_u_okviru_organizacije_drugo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Додатно образовање друго'),
        ),
    ]
