# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0051_auto_20170830_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitanje3_2',
            name='Nacin_skladistenja_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Начин складиштења остало'),
        ),
    ]
