# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0052_pitanje3_2_nacin_skladistenja_ostalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitanje3_2',
            name='Format_Distribucije_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Формат Дистрибуције остало'),
        ),
        migrations.AddField(
            model_name='pitanje3_2',
            name='Nacin_Distribucije_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Начин Дистрибуције остало'),
        ),
    ]
