# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0058_auto_20170911_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='saradnjaizmedjusubjekata',
            name='Problemi_prilikom_nabavke_geopodataka_drugo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Проблеми приликом набавке геоподатака друго'),
        ),
    ]
