# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0059_saradnjaizmedjusubjekata_problemi_prilikom_nabavke_geopodataka_drugo'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizacijaotvorenihpodataka',
            name='Metode_koriscenja_i_zastite_drugo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Методе коришћења и заштите друго'),
        ),
    ]
