# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0060_standardizacijaotvorenihpodataka_metode_koriscenja_i_zastite_drugo'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizacijaotvorenihpodataka',
            name='Da_li_podrzavate_prikupljanje_geopodataka_prema_konceptu_otvorenih_podataka_drugo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Прикупљање према концепту отворениох података друго'),
        ),
    ]
