# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0061_standardizacijaotvorenihpodataka_da_li_podrzavate_prikupljanje_geopodataka_prema_konceptu_otvorenih_'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizacijaotvorenihpodataka',
            name='Da_li_ste_koristili_besplatne_setove_podataka_drugo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Да ли сте користили бесплатне сетове података друго'),
        ),
        migrations.AddField(
            model_name='standardizacijaotvorenihpodataka',
            name='Da_li_ste_upoznati_sa_nekim_od_postojecih_portala_drugo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Да листе упознати са неким од постојећих портала друго'),
        ),
    ]
