# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0062_auto_20170911_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizacijaotvorenihpodataka',
            name='Za_koje_poslove_ste_koristili_podatke_drugo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='За које послове сте користили податке друго'),
        ),
    ]
