# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0063_standardizacijaotvorenihpodataka_za_koje_poslove_ste_koristili_podatke_drugo'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizacijaotvorenihpodataka',
            name='Format_podataka_drugo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='У ком формату су били преузети подаци друго'),
        ),
    ]
