# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0066_standardizacijaotvorenihpodataka_sufinansiranje_podataka_drugo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitanje3_2',
            name='Period_Azuriranja_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Период ажурирања остало'),
        ),
    ]
