# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0067_pitanje3_2_period_azuriranja_ostalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitanje5_4',
            name='Naziv_akta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
