# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0068_auto_20170919_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitanje5_12',
            name='Prepreka2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitanje5_12',
            name='Prepreka3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
