# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0071_auto_20170919_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sveobuhvatnimodel',
            name='Cetvrta_sekcija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.SaradnjaIzmedjuSubjekata', unique=True),
        ),
        migrations.AlterField(
            model_name='sveobuhvatnimodel',
            name='Druga_sekcija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.KadroviInfrastruktura', unique=True),
        ),
        migrations.AlterField(
            model_name='sveobuhvatnimodel',
            name='Peta_sekcija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.StandardizacijaOtvorenihPodataka', unique=True),
        ),
        migrations.AlterField(
            model_name='sveobuhvatnimodel',
            name='Prva_sekcija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.OrganizacijaOsnovniPodaci', unique=True),
        ),
        migrations.AlterField(
            model_name='sveobuhvatnimodel',
            name='Treca_sekcija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.ProstorniPodaci', unique=True),
        ),
    ]
