# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0072_auto_20170919_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitanje2_5',
            name='Program',
            field=models.CharField(choices=[('ArcGIS Desktop (ESRI)', 'ArcGIS Desktop (ESRI)'), ('Q GIS', 'Q GIS'), ('MapInfo', 'MapInfo'), ('GeoMedia', 'GeoMedia'), ('MapSoft', 'MapSoft'), ('AutoCAD', 'AutoCAD'), ('Bently MicroStation', 'Bently MicroStation'), ('ERDAS IMAGINE', 'ERDAS IMAGINE'), ('Leica Photogrametry Suite', 'Leica Photogrametry Suite'), ('eCognition Trimble', 'eCognition Trimble'), ('Интерно креиране апликације', 'Интерно креиране апликације'), ('Остало', 'Остало')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje5_2',
            name='Standard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pitanje5_2',
            name='Upotreba',
            field=models.TextField(blank=True, null=True),
        ),
    ]
